# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f906fdd42aea3a5589d2ca1a38ed81007fa2c614693ec89a48213e5491f169588cf8959eec741fab7fcb3c8c102033b4b72136825b64aea871fcb6730dc06d4

test:
  secret_key_base: eff10c84563404dbc26baa23280fc8329a7a4533a661ff14083fb1ff6d220a9e6708166ca6536aa9dfdf0d70629005975ba59841f0c2e128750cac551e93ab46

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
